# Generated by Django 4.0.7 on 2023-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_employee_task1_employee_task2_employee_task3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
