# Generated by Django 4.0.7 on 2023-08-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assign_task',
            field=models.BooleanField(default=False),
        ),
    ]
