# Generated by Django 4.0.7 on 2023-08-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_employee_assign_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_report',
            field=models.BooleanField(default=False),
        ),
    ]
